# kubectl apply -f=service.yaml
# kubectl delete -f=service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector:
  # service의 selector api는 deployment보다 이전 버전이라서 Deployment와 달리 matchLabels가 필요없다.
    app: second-app # second-app을 가진 Deployment들을 이 service로 묶으려면 app: second-app만 작성하면 됨.
  ports:
    - protocol: 'TCP' # default: TCP임
      port: 80
      targetPort: 8082
    # 여러 port가 있는 경우 아래처럼 추가로 다중 선언 가능
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer # minikube를 사용하고 있으므로 minikube에서 지원해주는 로드밸런서를 사용함