# hostPath 유형의 영구 볼륨
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi # 용량 1GB
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # 이 볼륨이 단일 노드에 의해, 읽기/쓰기 볼륨으로 마운트 될 수 있음을 의미
    # - ReadOnlyMany # 읽기 전용으로 여러 노드에서 요청할 수 있음을 의미
    # - ReadWriteMany # 쓰기 전용으로 여러 노드에서 요청할 수 있음을 의미
  hostPath:
    path: /data
    type: DirectoryOrCreate