version: "3"
services:
  auth:
    build: ./auth-api
  users:
    build: ./users-api
    environment:
      AUTH_ADDRESS: auth
      AUTH_SERVICE_SERVICE_HOST: auth
    ports: 
      - "8081:8080"
  tasks:
    build: ./tasks-api
    ports: 
      - "8001:8000"
    environment:
      TASKS_FOLDER: tasks
    
